### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by maximpetrov** [Phambanam/zadania1#1]
1. Простые классы, такие как `Person` и `Address` следует делать неизменяемыми (immutable). То есть все их поля нужно задавать через конструктор и не делать set-методы, только get-методы.
1. Методы, предназначенные для использования пользователями класса, нужно делать `public`, а не package private, иначе они не будут доступны за пределами пакета. (У Вас это все методы)
1. Зачем Вам `getAddressBook`? Этот метод позволяет получить внутренний `Map` и сломать его. Если Вам он нужен для сравнения в тестах, то лучше переопределите метод `equals` для Вашего класса. Его в любом случае стоит переопределить.
1. Классам `Person` и `Address` не хватает методов `equals` и  `hashCode`.
1. В `AddressBook` не хватает метода для получения адреса человека.
1. https://github.com/Phambanam/zadania1/blob/ef4d4fb4d3f2f544b65c0c1a4c635a374677b5a7/src/main/java/AddressBooks/AddressBook.java#L14-L18 Зачем здесь ловить `NullPointerException`?
1. Зачем искать перебором в `Map` в `edit` и `remove`, если можно воспользоваться `containsKey`? К тому же, Вам вообще искать не нужно, можно просто вызвать `replace` и `remove`. 
1. В методах `add`, `edit` и `remove` следует как-то информировать пользователя о том, что изменений не было: если человек уже есть в `Map`, то добавлять его в `add` не стоит. То же самое в `edit` и `remove` - если человека нет, то делать ничего не нужно. Вот об этих ситуациях нужно сообщить пользователю, например, возвращаемым `boolean` значением.
1. Тесты `add` и `remove` у Вас ничего не проверяют, так как в них нет assert.

**Comment by Phambanam** [comment]
простите мне!
я не знаю ,что вы уже ответил давно!
Сейчас я уже соmmit новый решение 
Пж , проверите мне!

**Comment by maximpetrov** [comment]
1. Зачем Вы убрали `getName()` из `Person`? Как теперь получать имя человека? `toString()` возвращает имя, но этот метод предназначен не для этого. Пользователь Вашего класса не обязан догадываться, что для получения имени нужно использовать `toString()`, тем более, что Вы можете этот метод поменять и он перестанет возвращать просто имя.
1. Методы `getStress`, `getHouse` и `getApartment` в `Address` всё ещё не `public` и все методы `AddressBook` тоже.
1. Метод `equals` должен сначала проверять переданный объект на равенство себе по ссылке и на `null`.
1. Вывод в консоль не считается за информирование пользователя. Во-первых, Ваш класс может использоваться в приложении с графическим интерфейсом, в котором вообще нет консоли. Во-вторых, я имел в виду не пользователя приложения, а пользователя класса, то есть программиста, который использует Ваш класс. Он никак не сможет программно узнать было ли добавление, удаление и т.п. успешным, если Вы будете только печатать сообщение в консоль. Настоящие способы информирования - возвращаемое значение или исключение. К тому же, если приложение всё-таки консольное, то непрошенный вывод в консоль может мешать.
1. https://github.com/Phambanam/zadania1/blob/e0f97f1ec4c528e06d67118e9995472348c1e60f/src/main/java/AddressBooks/AddressBook.java#L45-L46 В этой ситуации `replace` никогда не добавит элемент в `Map`, потому что она только заменяет значение ключа, который уже есть, а Вы его сначала удаляете.
1. На самом деле, Вам не нужен `containsKey` в Ваших методах. `get`, `remove`, `replace` и `putIfAbsent` возвращают значение, по которому можно понять, был ключ или нет.
1. Тесты `add`, `remove` и `edit` всё ещё ничего не проверяют.

**Comment by Phambanam** [comment]
я уже исправил

**Comment by maximpetrov** [comment]
1. `setError` не нужен у `myException`, достаточно задавать его в конструкторе.
1. Повторю, `containsKey` из методов `AddressBook` лучше убрать, чтобы не искать ключ по два раза. Лучше сразу вызвать нужный метод, например, `get` и проанализировать его возвращаемое значение.
1. Метод `getAddressBook`, если он Вам действительно нужен, должен возвращать копию `Map`, иначе можно случайно испортить внутренний `Map`, поменяв возвращённое значение.

**Comment by Phambanam** [comment]
Если я не использую containskey, как я могу уведомить пользователя, что они добавили (add) существующего person?

**Comment by maximpetrov** [comment]
Используйте `putIfAbsent` и проверьте возвращаемое значение

**Comment by Phambanam** [comment]
я понял

**Comment by maximpetrov** [comment]
`remove` и `edit` Вы исправили почти верно, но повторные вызовы `remove` и `replace` там не нужны. `add` нужно реализовать так же, как эти два метода, только нужно проверить наоборот, что `putIfAbsent` вернул не `null`. Это будет означать, что такой ключ уже был.

**Comment by Phambanam** [comment]
Я исправил

**Comment by maximpetrov** [comment]
Принято
